<a href="https://colab.research.google.com/github/ValentynaGrach/ml-homeworks/blob/main/%D0%94%D0%97_2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import library
import numpy as np

from numpy import pi

In [ ]:
!pip install numpy==1.24
np.__version__

'1.24.0'



---



In [ ]:
# a = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=object, delimiter=',', usecols=(0,1,2,3,4))
# print(a[:5])
# print("Dataset form:", a.shape)
# print(a.dtype)

In [ ]:
# a = np.delete(a, 4, axis=1)
# print(a[:5])
# print("Dataset form:", a.shape)
# print(a.dtype)



---



1. Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [ ]:
iris =np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=float, delimiter=',', usecols=(0,1,2,3))
print(iris[:5])
print("Dataset form:", iris.shape)
print(iris.dtype)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Dataset form: (150, 4)
float64




---



2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)

In [ ]:
print("Num Dimensions: ", iris.ndim)
print("Dataset form:", iris.shape)
print(type(iris))
print(iris[:5])

Num Dimensions:  2
Dataset form: (150, 4)
<class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]




---



3. Порахувати mean, median, standard deviation для 1-ї колонки

In [ ]:
print("Column wise mean 1: ", np.mean(iris, axis=0)[0])
print("Column wise median 1: ", np.median(iris, axis=0)[0])
print("Column wise standard deviation 1: ", np.std(iris, axis=0)[0])

Column wise mean 1:  5.843333333333335
Column wise median 1:  5.8
Column wise standard deviation 1:  0.8253012917851409




---



4. Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

In [ ]:
np.random.seed(100)

iris[np.unravel_index(np.random.choice(iris.size, size=20, replace=False), iris.shape)] = np.nan

nan_positions = np.where(np.isnan(iris))
print("Кількість значень np.nan:", len(nan_positions[0]))
print("Позиції значень np.nan:", list(zip(nan_positions[0], nan_positions[1])))
print("Чи є 20 np.nan?", len(nan_positions[0]) == 20)

print("Dataset form:", iris.shape)
print(iris[:5])

Кількість значень np.nan: 20
Позиції значень np.nan: [(12, 0), (18, 3), (26, 2), (29, 2), (31, 1), (35, 2), (37, 1), (43, 1), (59, 3), (64, 1), (67, 2), (76, 2), (89, 3), (90, 0), (91, 1), (104, 2), (106, 0), (124, 2), (138, 2), (143, 3)]
Чи є 20 np.nan? True
Dataset form: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]




---



5. Знайти позиції вставлених значень np.nan в 1-й колонці

In [ ]:
print("nan_positions: ", np.where(np.isnan(iris[:, 0]))[0])

nan_positions:  [ 12  90 106]




---



6. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

In [ ]:
filtered_iris = iris[(iris[:, 2] > 1.5) & (iris[:, 0] < 5.0)]

print("Dataset form:", iris.shape)
print(iris[:5])
print("Dataset form:", filtered_iris.shape)
print(filtered_iris)

Dataset form: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Dataset form: (4, 4)
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]]




---



7. Замінити всі значення np.nan на 0

In [ ]:
iris[np.isnan(iris)] = 0
print("Positions of replaced values:", np.where(iris == 0))

Positions of replaced values: (array([ 12,  18,  26,  29,  31,  35,  37,  43,  59,  64,  67,  76,  89,
        90,  91, 104, 106, 124, 138, 143]), array([0, 3, 2, 2, 1, 2, 1, 1, 3, 1, 2, 2, 3, 0, 1, 2, 0, 2, 2, 3]))




---



8. Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

12. Знайти найбільш часто повторюване значення в массиві

In [ ]:
uniqs, counts = np.unique(iris, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

Unique items :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9]
Counts       :  [20  6 28  6  7  1  1  8  4  6 19 19 26  9  6 12  7  7  6  6 11  6 11  5
  9 14  9 26 11 13  8 11  7  4  4  7  5  6  3  5  3  8  9  7  7  6 10 14
 17  6  3  8  9 12 10  9  5  8  9  4 10  8  5  3 10  3  5  1  1  3  1  1
  1  4  1]




---



9. Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [ ]:
iris1, iris2 = np.split(iris, 2, axis=0)

print("Dataset form:", iris1.shape)
print("Dataset form:", iris2.shape)
print("_________" * 10)
print(iris1[:5])
print("_________" * 10)
print(iris2[:5])

Dataset form: (75, 4)
Dataset form: (75, 4)
__________________________________________________________________________________________
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
__________________________________________________________________________________________
[[6.6 3.  4.4 1.4]
 [6.8 2.8 0.  1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]]




---



10. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [ ]:
iris1 = iris1[np.argsort(iris1[:, 0])]
iris2 = iris2[np.argsort(iris2[:, 0])[::-1]]

print("Sorted upper:")
print(iris1)
print("_________" * 10)
print("Sorted lower:")
print(iris2)

Sorted upper:
[[0.  3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 0.  0.2]
 [4.8 3.  1.4 0.3]
 [4.8 3.4 1.9 0.2]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.9 0.  1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [5.  0.  1.6 0.6]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.  3.4 1.5 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 0.  0.4]
 [5.  2.  3.5 1. ]
 [5.  3.6 1.4 0.2]
 [5.  3.2 0.  0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.5 0.3]
 [5.1 3.7 1.5 0.4]
 [5.1 3.3 1.7 0.5]
 [5.2 2.7 3.9 0. ]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.3 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.4 3.9 1.7 0.4]
 [5.4 0.  1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [5.5 2.3 4.  1.3]
 [5.5 4.2 1.4 0.2]
 [5.6 0.  3.6 1.3



---



11. Зібрати обидва массиви в одне ціле

In [ ]:
iris3 = np.concatenate([iris1, iris2], axis=0)

print("Dataset form:", iris3.shape)
print(iris3)

Dataset form: (150, 4)
[[0.  3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 0.  0.2]
 [4.8 3.  1.4 0.3]
 [4.8 3.4 1.9 0.2]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.9 0.  1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [5.  0.  1.6 0.6]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.  3.4 1.5 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 0.  0.4]
 [5.  2.  3.5 1. ]
 [5.  3.6 1.4 0.2]
 [5.  3.2 0.  0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.5 0.3]
 [5.1 3.7 1.5 0.4]
 [5.1 3.3 1.7 0.5]
 [5.2 2.7 3.9 0. ]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.3 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.4 3.9 1.7 0.4]
 [5.4 0.  1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [5.5 2.3 4.  1.3]
 [5.5 4.2 1.4 0.2]
 [5.6 0.



---



13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [ ]:
def modify_column(column):
    mean_val = np.mean(column)
    column = np.where(column < mean_val, column * 2, column / 4)
    return column

14. Застосувати отриману функцію до 3-ї колонки

In [ ]:
iris3[:, 2] = modify_column(iris3[:, 2])
print(iris3)

[[0.    3.    2.8   0.1  ]
 [4.3   3.    2.2   0.1  ]
 [4.4   2.9   2.8   0.2  ]
 [4.4   3.2   2.6   0.2  ]
 [4.4   3.    2.6   0.2  ]
 [4.5   2.3   2.6   0.3  ]
 [4.6   3.1   3.    0.2  ]
 [4.6   3.4   2.8   0.3  ]
 [4.6   3.2   2.8   0.2  ]
 [4.6   3.6   2.    0.2  ]
 [4.7   3.2   2.6   0.2  ]
 [4.7   3.2   0.    0.2  ]
 [4.8   3.    2.8   0.3  ]
 [4.8   3.4   3.8   0.2  ]
 [4.8   3.1   3.2   0.2  ]
 [4.8   3.4   3.2   0.2  ]
 [4.9   0.    3.    0.1  ]
 [4.9   3.1   3.    0.1  ]
 [4.9   2.4   6.6   1.   ]
 [4.9   3.1   3.    0.1  ]
 [4.9   3.    2.8   0.2  ]
 [5.    0.    3.2   0.6  ]
 [5.    3.3   2.8   0.2  ]
 [5.    3.5   2.6   0.3  ]
 [5.    3.4   3.    0.2  ]
 [5.    3.    3.2   0.2  ]
 [5.    3.4   0.    0.4  ]
 [5.    2.    7.    1.   ]
 [5.    3.6   2.8   0.2  ]
 [5.    3.2   0.    0.2  ]
 [5.1   3.8   3.8   0.4  ]
 [5.1   3.4   3.    0.2  ]
 [5.1   3.8   3.2   0.2  ]
 [5.1   3.5   2.8   0.2  ]
 [5.1   3.5   2.8   0.3  ]
 [5.1   3.8   3.    0.3  ]
 [5.1   3.7   3.    0.4  ]
 